### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by tmitchell1** [GoMexSI/interaction-data#1]
Jorrit,
I have discovered dome problems and a huge chunk of missing data. They mainly have to do with 2 upload dates. The first would have been around 07/21/2014 and the 2nd around 08/01/2014.

List of references for the 07/21/2014 chunk: 34b, 46b, 51b, 4d, 10d, 20d, 23d, 11f, 5g, 28g, 32g, 4h, 15h, 5j, 13l, 9n, 4p, 2r, 5r, 35r, 26s, 76s, 79s, 8w. All but two of the references (46b, 20d) are completely missing from all the spreadsheets.

List of references for 08/01/2014 chunk: 5a, 14b, 2c, 26f, 8n, 57s. All of these references only appear in the "REFERENCES" spreadsheet and in none of the others.

Finally, 12c (one of Simons early entries) is also only listed in the "REFERENCES" spreadsheet and in none of the others.

Do you have the data somewhere? Did something accidentally get erased? Do I need to just recopy all of the missing data into Github?

Thanks.

**Comment by jhpoelen** [comment]
Hi Theresa! 

According to the github history, the last change to the gomexsi data at the "old" location occurred in this commit on Aug 1, 2014 (see [here](https://github.com/jhpoelen/eol-globi-data/tree/master/eol-globi-data-tool/src/main/resources/org/eol/globi/data/gomexsi)). This change was made by you to the references.csv file, including but not limited to `5a`, `14b`, `2c`.

Other files (e.g. `locations.csv`, `prey.csv`, `predator.csv`, `methods.csv`) where last updated on July 25, 2014 (see [commit](https://github.com/jhpoelen/eol-globi-data/commit/69889272d7a6bd68665216d78ec92681f7ef3a49#diff-c5be3a05676f38d78fcd1697363bf1b2) ). This update includes studies like 41b, 43b and more.

I have no evidence of data being accidentally erased, so most likely the data was never added for some reason (perhaps still sitting in an email attachment). I like your suggestion to re-add the data to github. Let me know if you'd like me to verify the result once you're done with this.

Hope this helps. Please re-open the issue if you need more help.

-jorrit
