### ISSUE TITLE
additions

### ISSUE THREAD

**Issue by tmitchell1** [GoMexSI/interaction-data#12]
Jorrit,
Can you double check that the 2 changes I made today actually committed? I had to update my GitHub and when I tried to sync the changes I got the message "Failed yo sync this branch. You might need to open a shell and debug this repo."
Can you help me with what I need to do? Thanks

**Comment by jhpoelen** [comment]
Sorry to hear about your github sync problem. I just checked your commits on https://github.com/GoMexSI/interaction-data/commits/master and found that the last commit was back in August 2016.

Perhaps the easiest thing to do is to: (1) copy your edited csv files to a separate location (2) get a fresh copy of the github gomexsi/interactions repository. (3) copy the edited csv file into the fresh repository, overwriting the "fresh" csv files. (4) try to sync the repository.

If this does not work, please attach your csv files to this issue and I can have a look.

**Comment by tmitchell1** [comment]
Thanks. I followed your instructions. I think it worked. I should have added 15 references and 2,389 new prey lines.

**Comment by jhpoelen** [comment]
@tmitchell1 nice! I am glad you were able to add your new references and prey lines. Assuming that we can close this issue. Please re-open / comment if necessary.
