### ISSUE TITLE
create two empty interaction-data repositories

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/interaction-data#13]
As discussed with @jsimons9 today - suggest to create two repositories with GoMexSI/interaction-data structures, but no data. The repositories will be used by Michelle (grad student) and for the new gut data gathered using Marfin funds. By creating these repositories, GloBI can provide early feedback on data integrity of the archives as data gets added, so that error can be resolved as they get introduced.

@tmitchell1 please let me know if you need help setting up these repositories.

**Comment by tmitchell1** [comment]
@jhpoelen I have not created a new repository yet and I am not sure how. Maybe one day next week you can walk me through how to do it.

**Comment by jhpoelen** [comment]
Suggest to just give it a shot (look for "create github repository"), and if that doesn't work, please suggest date/time to chat.

**Comment by jhpoelen** [comment]
Repository at https://github.com/gomexsi/abascal was created a while ago. Closing issue.
