### ISSUE TITLE
possible invalid [lengthInMm] with value [SL]

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/interaction-data#16]
@tmitchell1 any thoughts on this one?

org.eol.globi.data.StudyImporterException: failed to parse key [lengthInMm] with value [SL]
	at org.eol.globi.data.StudyImporterForGoMexSI2.doubleValueOrNull(StudyImporterForGoMexSI2.java:309)
	at org.eol.globi.data.StudyImporterForGoMexSI2.createSpecimen(StudyImporterForGoMexSI2.java:315)
	at org.eol.globi.data.StudyImporterForGoMexSI2.addObservation(StudyImporterForGoMexSI2.java:262)
	at org.eol.globi.data.StudyImporterForGoMexSI2.addObservations(StudyImporterForGoMexSI2.java:185)
	at org.eol.globi.data.StudyImporterForGoMexSI2.importStudy(StudyImporterForGoMexSI2.java:105)
	at org.eol.globi.data.StudyImporterForGitHubData.importData(StudyImporterForGitHubData.java:86)
	at org.eol.globi.data.StudyImporterForGitHubData.importData(StudyImporterForGitHubData.java:59)
	at org.eol.globi.tool.GitHubRepoCheck.main(GitHubRepoCheck.java:86)
	at org.globalbioticinteractions.CmdCheck.run(CmdCheck.java:20)
	at org.globalbioticinteractions.CmdLine.run(CmdLine.java:15)
	at org.globalbioticinteractions.CmdLine.run(CmdLine.java:23)
	at org.globalbioticinteractions.Elton.main(Elton.java:9)
Caused by: java.lang.NumberFormatException: For input string: "SL"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.eol.globi.data.StudyImporterForGoMexSI2.doubleValueOrNull(StudyImporterForGoMexSI2.java:306)
	... 11 more

**Comment by tmitchell1** [comment]
I am not quite understanding this one. I need a bit more info. Is this in Abascal database or in the main one? Any idea what REF this coincides with?

**Comment by jhpoelen** [comment]
Here's some of the offending records from the Prey.csv - notice that PREY_MN_LEN values are not numbers, but terms like ```SL``` and ```FL```.  Related ref ACT_2I . It looks like the column headers might be misaligned.


DATA_ID | PRED_ID | PREY_SOURCE_NAME | PREY_DATABASE_NAME | BASIS_OF_PREY_ID | PHYSIOLOG_STATE | SED_ORIGIN | PREY_PARTS | PREY_LIFE_HIST_STAGE | PREY_COND_INDEX | PREY_SEX | PREY_SEX_RATIO | PREY_LEN_TYPE | PREY_MIN_LEN | PREY_MAX_LEN | PREY_MN_LEN | PREY_MIN_WIDTH | PREY_MAX_WIDTH | PREY_MN_WIDTH | BIOMASS | BIOMASS_QUALIFIER | PCT_BIOMASS | PCT_BIOMASS_QUALIFIER | N_CONS | N_CONS_QUALIFIER | PCT_N_CONS | PCT_N_CONS_QUALIFIER | VOL_CONS | VOL_CONS_QUALIFIER | PCT_VOL_CONS | PCT_VOL_CONS_QUALIFIER | FREQ_OCC | FREQ_OCC_QUALIFIER | PCT_FREQ_OCC | PCT_FREQ_OCC_QUALIFIER | IRI | PCT_IRI | IRIa | IIR | E | PREY_NOTES | ENTRY_DATE | ENTRY_PERSON | EDITED_DATE | DATA_EDITOR | MODIFY_DATE | DATA_MODIFIER |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ACT_2I | Mund.1 | none | Micropogon undulatus | Micropogonias undulatus | gut content | 868 | 788 | 90.8 | 80 | 9.2 | NA | NA | NA | NA | SL | 12 | 106 | 40 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Care.1 | none | Cynoscion arenarius | Cynoscion arenarius | gut content | 216 | 193 | 89.3 | 23 | 10.7 | NA | NA | NA | NA | SL | 23 | 105 | 46 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Cneb.1 | none | Cynoscion nebulosus | Cynoscion nebulosus | gut content | 26 | 17 | 65.4 | 9 | 34.6 | NA | NA | NA | NA | SL | 81 | 125 | 102 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Soce.1 | none | Sciaenops ocellatus | Sciaenops ocellatus | gut content | 52 | 46 | 88.5 | 6 | 11.5 | NA | NA | NA | NA | SL | 30 | 101 | 60 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Bmar.1 | none | Bagre marinus | Bagre marinus | gut content | 32 | 29 | 90.6 | 3 | 9.4 | NA | NA | NA | NA | FL | 52 | 91 | 71 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Gfel.1 | none | Galeichthys felis | Ariopsis felis | gut content | 13 | 13 | 100 | 0 | 0 | NA | NA | NA | NA | FL | 48 | 210 | 107 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Lxan.1 | none | Leiostomus xanthurus | Leiostomus xanthurus | gut content | 35 | 28 | 80 | 7 | 20 | NA | NA | NA | NA | SL | 18 | 143 | 58 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Cspi.1 | none | Citharichthys spilopterus | Citharichthys spilopterus | gut content | 71 | 23 | 32.4 | 48 | 67.6 | NA | NA | NA | NA | SL | 53 | 83 | 64 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Plet.1 | none | Paralichthys lethostigma | Paralichthys lethostigma | gut content | 14 | 11 | 78.6 | 3 | 21.4 | NA | NA | NA | NA | SL | 18 | 160 | 114 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | examination of flounder stomachs incomplete | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Lrho.1 | none | Lagodon rhomboides | Lagodon rhomboides | gut content | 11 | 11 | 100 | 0 | 0 | NA | NA | NA | NA | SL | 87 | 115 | 107 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | empty stomachs and empty intestines | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Tmac.1 | none | Trinectes maculatus | Trinectes maculatus | gut content | 10 | 5 | 50 | 5 | 50 | NA | NA | NA | NA | SL | 34 | 48 | 41 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | examination of stomachs inconclusive | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Gbos.1 | none | Gobiosoma bosc | Gobiosoma bosc | gut content | 9 | 9 | 100 | 0 | 0 | NA | NA | NA | NA | SL | 29 | 51 | 41 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Pcro.1 | none | Pogonias cromis | Pogonias cromis | gut content | 6 | 6 | 100 | 0 | 0 | NA | NA | NA | NA | SL | 131 | 158 | 141 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Otau.1 | none | Opsanus tau | Opsanus tau | gut content | 6 | 0 | 0 | 6 | 100 | NA | NA | NA | NA | SL | 117 | 162 | 146 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | Intestines of Oyster Dog all contained remains of a species of mud crab | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell
ACT_2I | Bchr.1 | none | Bairdiella chrysoura | Bairdiella chrysoura | gut content | 5 | 4 | 80 | 1 | 20 | NA | NA | NA | NA | SL | 46 | 90 | 57 | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 9/2/2016 | Rebecca Lund | 10/6/2016 | Rebecca Lund | 12/12/2016 | Theresa Mitchell

**Comment by tmitchell1** [comment]
How old are the files you are running the tests on? My repository files were cloned on 9/15/17 so that I could work from home. The Predator file I have shows the "SL" and "FL" in the correct column of PRED_LEN_TYPE_1.  Any thoughts?

**Comment by jhpoelen** [comment]
I am looking at the files related to 090893a054c6d80a9a6b3f640851ddb3d70e1bec . As far as I can tell, this is the most recent version. Please note that the values I shared before came from the Prey.csv file.

**Comment by tmitchell1** [comment]
Apologies. I was mistakenly looking at the PRED sheet. Issue has been fixed.
