### ISSUE TITLE
Predator list

### ISSUE THREAD

**Issue by tmitchell1** [GoMexSI/interaction-data#2]
In the Predator list, under the DATA_AGGR_CODE column: codes are getting changed somewhere along the line.
Examples: the code "size" is uploaded but then some how ends up becoming "sizee," "location" ends up as "locationation" and "season" ends up as "seasonson."
I have fixed everything (I think) as of today and uploaded the changes.

**Comment by jhpoelen** [comment]
hi @tmitchell1! Could you please be more specific? I am not quite sure whether this a question, bug or a notification.

**Comment by tmitchell1** [comment]
I am not really sure either. I know when the data was originally uploaded, the aggregation codes were correct. However after I had downloaded the csv files locally for changes/additions, the codes had somehow changed. I am not sure where along the way they could have been changed.

**Comment by jhpoelen** [comment]
GitHub does not automatically change data, so the change must have been made by someone somewhere. 
My questions: 
1. Does the current dataset in gomexsi/interaction-data have the correct aggregation codes?
2. When did you do the original upload? Do you show me the github commit where this happened?

**Comment by tmitchell1** [comment]
The current dataset should have all the codes corrected, as I made the changes when I updated the other day. This happened sometime before December, when I downloaded the files to be able to make changes locally. There were about 6 uploads before I noticed the errors. Hopefully the problem has been corrected. I mainly just wanted you to be aware of this just in case we come across it again.

**Comment by jhpoelen** [comment]
Thanks for clarifying and correcting the issue!
