### ISSUE TITLE
non-number values like "< 0.005" and "> 0.005" encountered in numeric fields

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/interaction-data#8]
Various values of non numeric values are found in numeric fields.

Examples include:

```
"na"
"> .001"
"tr"
"< 2"
"> .005
"< .005"
"< 0.0001"
"*"
```

Suggest to either (a) remove the offending values or (b) introduce the concept of a numeric range with min and max column. Example for (b) would be to introduce something like totalNumberConsumedPercentMin and totalNumberConsumedPercentMax . In case of a value like "< 0.005" totalNumberConsumedPercentMax would be set to 0.0005 and the totalNumberConsumedPercentMin would be 0. 

Note that these non-numeric values are currently interpreted as no value by GloBI.

**Comment by jsimons9** [comment]
Hi Jorrit,

  Thanks for the note on this. Let me give this some thought as to how to handle it.

Jim

**Comment by jsimons9** [comment]
After conferring with our statistician here at CCS, I have decided that we will add an additional column to take care of the < , TR, and NA values for those variables that are most affected by this. I am not sure exactly how many columns of data are thus affected, but we do have 2 or 3 that we need to attend to.

**Comment by tmitchell1** [comment]
New columns added to take care of qualifiers.
